---
title: "data-wrangling"
author: "M. Gabriela Puscama"
date: "7/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r Load Packages}

library(tidyverse)
library(stringr) #To modify text in string data.
library(phonR) #To transform formant frequencies to Bark

```

```{r Load Data Files}

#Main Data Set
data_raw <- read.csv("./data/formants(1-5).csv")
head(data_raw)
summary(data_raw)

#Demographic and Proficiency Information
lhq <- read.csv("./data/SuppData/Demographics_Proficiency.csv")
head(lhq)

```

```{r Format Columns}

data_raw <- data_raw %>%
  separate(Segment_num, c("participant", "trialN", "word", "repetitionN")) %>% #Separate segment column into participant, trial number, word, and repetition number
  mutate(participant=str_replace_all(participant, "[:alpha:]", "")) %>% #Eliminate participant letter code and keep number
  mutate(participant=as.character(participant)) %>%
  mutate(participant=str_replace_all(participant, "0", "en0")) %>% #Add L1 as part of the code
  rename(duration=Duration, start=Start_time, time=Time) %>% #Make all columns lower case
  select("participant", #Keep columns of interest
         "trialN",
         "word",
         "repetitionN",
         "duration",
         "start",
         "time",
         "F0",
         "F1",
         "F2",
         "F3")

View(data_raw)

```

```{r Update LHQ Codes and Add to Main Dataset}

lhq <- lhq %>% 
  mutate(participant=str_replace_all(Participant, "[:alpha:]", "")) %>% 
  mutate(participant=as.character(participant)) %>%
  mutate(participant=str_replace_all(participant, "0", "en0")) %>%
  rename(vfEng=VF_English, vfSpan=VF_Spanish, ldtEng_d=LDT_English_d, ldtSpan_d=LDT_Spanish_d, ldtEng_a=LDT_English_A, ldtSpan_a=LDT_Spanish_A)%>%
  select("participant",
         "age",
         "gender",
         "L1",
         "vfEng",
         "vfSpan",
         "ldtEng_d",
         "ldtSpan_d",
         "ldtEng_a",
         "ldtSpan_a")
  
data <- left_join(data_raw,lhq)

View(data)
```

```{r Transform Formants from Hz to Bark}

data <- data %>% #Normalize F1 and F2 measurements by transforming to Bark with phonR package
  mutate(barkF1=normBark(F1), barkF2=normBark(F2))

View(data)

```

```{r Save Clean Dataset}

write.csv(data,"./data/data_clean(1-5).csv")

```


